name: Frontend CI/CD (Self-Hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Docker Container
        run: |
          cd /var/www/karbama/frontend
          git pull origin main
          cd /var/www/karbama
          docker compose up -d --build frontend
