name: Frontend CI/CD (Self-Hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Docker Container
        run: |
          git config --global --add safe.directory /var/www/karbama/frontend
          
          cd /var/www/karbama/frontend
          sudo git pull origin main
          
          cd /var/www/karbama
          sudo docker compose up -d --build frontend
